---
pipelines:
- name: Cloud Foundry
  tag: cf
  filter:
    using_bosh_releases: [cf]
- name: RDPG
  tag: rdpg
  filter:
    using_bosh_releases: [rdpg]
- name: Logstash Service
  tag: logstash-service
  filter:
    using_bosh_releases: [docker, logstash-docker]
tiers:
  - name: try-anything
    columns:
      - name: bosh-lite
        filter:
          deployment_name_regexp: try-anything
  - name: internal-datacenter
    columns:
      - name: sandbox
        filter:
          bosh_uuid: uuid-vsphere-bosh-sandbox
      - name: preprod
        filter:
          bosh_uuid: uuid-vsphere-bosh-preprod
      - name: production
        filter:
          bosh_uuid: uuid-vsphere-bosh-production
  - name: aws-us-east-1
    columns:
      - name: sandbox
        filter:
          bosh_uuid: uuid-aws-bosh-sandbox
      - name: preprod
        filter:
          bosh_uuid: uuid-aws-bosh-preprod
      - name: production
        filter:
          bosh_uuid: uuid-aws-bosh-production
