---
auth:
  username: admin
  password: admin
pipelines:
- name: Redis
  tag: redis
  filter:
    using_bosh_releases: [redis]
- name: BPM
  tag: bpm
  filter:
    using_bosh_releases: [bpm]
tiers:
  - name: local
    slots:
      - name: warden-cpi
        filter:
          deployment_name_regexp: .*
  - name: dc
    slots:
      - name: sandbox
        filter:
          bosh_uuid: uuid-vsphere-bosh-sandbox
      - name: preprod
        filter:
          bosh_uuid: uuid-vsphere-bosh-preprod
      - name: production
        filter:
          bosh_uuid: uuid-vsphere-bosh-production
  - name: aws
    slots:
      - name: sandbox
        filter:
          bosh_uuid: uuid-aws-bosh-sandbox
      - name: preprod
        filter:
          bosh_uuid: uuid-aws-bosh-preprod
      - name: production
        filter:
          bosh_uuid: uuid-aws-bosh-production
